#!/bin/bash
####################################
#####
###
##
#
#
# Startup Script for the Application
####################################
set -e
. _lib.sh
RootCheck
echo "Starting [TheNovaDiary]"

# Mount the SSHFS ZFS volume
sshfs novix@nivenly.com:Pictures /home/nova/AlicePictures

docker run \
  -d \
  --name photoprism \
  --security-opt seccomp=unconfined \
  --security-opt apparmor=unconfined \
  -p 8081:2342 \
  -e PHOTOPRISM_UPLOAD_NSFW="true" \
  -e PHOTOPRISM_ADMIN_PASSWORD="charlie" \
  -v /home/nova/AlicePictures \
  photoprism/photoprism:latest

